from sdr1khw import *

openRig("/dev/parport0")
setRFE_Enabled(TRUE)
ResetRFE()
setXVTR_Enabled(FALSE)
setExtended(FALSE)
setXVTR_TR_Logic(FALSE)
setBandRelay(bs0)
RigInit()
setVFOOffset(0.0)
setATTN_Relay(TRUE)
setTransmitRelay(FALSE)
setGainRelay(TRUE)
setSpurReduction(FALSE)
setExternalOutput(FALSE)
setDDSClockCorrection(0.0)
setDDSFreq(13.845)
setMuteRelay(FALSE)
