#!/bin/sh

CMDPIPE=./IPC/SDR-1000-0-commands.fifo

while true
do
  read -p "command: " -e cmdline
  if [ $? -ne 0 ]
  then
    break
  fi
  sendline="$cmdline"
  echo $sendline
done | m4 -e enums.m4 - >$CMDPIPE
